/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["read_root__get"];
  };
  "/users/login": {
    post: operations["login_users_login_post"];
  };
  "/users/": {
    get: operations["get_users__get"];
    post: operations["signup_users__post"];
  };
  "/access-points/{id}": {
    /** Returns JSON containg current configuration of the Access Point with given database id. */
    get: operations["get_ap_config_by_id_access_points__id__get"];
    /**
     * Endpoint for changing Access Point's configuration. The request must be accompanied with a JSON (formatted like the result of the GET request to this endpoint) that contains only the values to be changed.
     *
     * **WARNING**: Parameters [`id`, `deviceId`, `ip`] **CANNOT** be changed.
     */
    put: operations["change_ap_config_access_points__id__put"];
  };
  "/access-points/": {
    /**
     * Returns a paginated JSON result of all Access Points which have the given string as part of their name.
     * Returned list can be an empty list.
     */
    get: operations["get_ap_configs_access_points__get"];
  };
  "/console/": {
    post: operations["cmd_input_console__post"];
  };
}

export interface components {
  schemas: {
    /**
     * APSchema
     * @example {
     *   "deviceId": 5,
     *   "id": 1,
     *   "ip": "192.168.1.6",
     *   "name": "Floor 1 AP",
     *   "networks": [
     *     {
     *       "id": 2,
     *       "name": "Guests"
     *     },
     *     {
     *       "id": 3,
     *       "name": "Employees"
     *     }
     *   ]
     * }
     */
    APSchema: {
      /** Id */
      id: number;
      /** Deviceid */
      deviceId: number;
      /** Name */
      name: string;
      /** Ip */
      ip: string;
      /** Networks */
      networks: components["schemas"]["NetworkNameSchema"][];
    };
    /**
     * CmdSchema
     * @example {
     *   "args": [
     *     "variables"
     *   ],
     *   "cmd": "show"
     * }
     */
    CmdSchema: {
      /** Cmd */
      cmd: string;
      /** Args */
      args: string[];
    };
    /** GetAPsSchema */
    GetAPsSchema: {
      /** Docs */
      docs: components["schemas"]["APSchema"][];
      /** Totaldocs */
      totalDocs: number;
      /** Totalpages */
      totalPages: number;
      /** Hasnextpage */
      hasNextPage: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * NetworkNameSchema
     * @example {
     *   "id": 1,
     *   "name": "Guests"
     * }
     */
    NetworkNameSchema: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /** NetworkSetSchema */
    NetworkSetSchema: {
      /** Id */
      id: number;
    };
    /** PutAPSchema */
    PutAPSchema: {
      /** Name */
      name?: Partial<string> & Partial<unknown>;
      /** Networks */
      networks?: Partial<components["schemas"]["NetworkSetSchema"][]> &
        Partial<unknown>;
    };
    /**
     * UserLoginCredentialsSchema
     * @example {
     *   "password": "password",
     *   "username": "user.name"
     * }
     */
    UserLoginCredentialsSchema: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** UserLoginResponseSchema */
    UserLoginResponseSchema: {
      /** Accesstoken */
      accessToken: string;
    };
    /**
     * UserSchema
     * @example {
     *   "firstName": "Name",
     *   "lastName": "Surname",
     *   "username": "user.name"
     * }
     */
    UserSchema: {
      /** Firstname */
      firstName: string;
      /** Lastname */
      lastName: string;
      /** Username */
      username: string;
    };
    /**
     * UserSignUpSchema
     * @example {
     *   "firstName": "Name",
     *   "lastName": "Surname",
     *   "password": "password",
     *   "username": "user.name"
     * }
     */
    UserSignUpSchema: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /** Firstname */
      firstName: string;
      /** Lastname */
      lastName: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (Partial<string> & Partial<number>)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  read_root__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  login_users_login_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserLoginResponseSchema"];
        };
      };
      /** Incorrect username or password */
      401: unknown;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserLoginCredentialsSchema"];
      };
    };
  };
  get_users__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
      /** Unauthorized */
      401: unknown;
      /** No user found */
      404: unknown;
    };
  };
  signup_users__post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
      /** User with the provided username already exists */
      409: unknown;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserSignUpSchema"];
      };
    };
  };
  /** Returns JSON containg current configuration of the Access Point with given database id. */
  get_ap_config_by_id_access_points__id__get: {
    parameters: {
      path: {
        id: unknown;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APSchema"];
        };
      };
      /** Invalid ID */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Endpoint for changing Access Point's configuration. The request must be accompanied with a JSON (formatted like the result of the GET request to this endpoint) that contains only the values to be changed.
   *
   * **WARNING**: Parameters [`id`, `deviceId`, `ip`] **CANNOT** be changed.
   */
  change_ap_config_access_points__id__put: {
    parameters: {
      path: {
        id: unknown;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Invalid ID */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PutAPSchema"];
      };
    };
  };
  /**
   * Returns a paginated JSON result of all Access Points which have the given string as part of their name.
   * Returned list can be an empty list.
   */
  get_ap_configs_access_points__get: {
    parameters: {
      query: {
        name?: Partial<string> & Partial<unknown>;
        page?: number;
        limit?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GetAPsSchema"];
        };
      };
      /** Unauthorized */
      401: unknown;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cmd_input_console__post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Unauthorized */
      401: unknown;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CmdSchema"];
      };
    };
  };
}

export interface external {}
